### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by bestming** [TProgram/mall-app-web#1]
建议你把GitHub的项目克隆到码云那里，那样才能让更多的人知道你的项目，然后fork。毕竟GitHub时不时抽风（众所周知的原因，），得用梯子才能正常访问，好多人开始转战码云了

**Comment by TProgram** [comment]
好的，谢谢您的关注，我这边抽时间放到码云上面一份🙏

**Comment by bestming** [comment]
> 好的，谢谢您的关注，我这边抽时间放到码云上面一份🙏

你的mall和mall-app-web建议搞个tag，不然同步了macro的仓库，如果他有大的改动，你这边的小程序就用不了了。

**Comment by bestming** [comment]
> 好的，谢谢您的关注，我这边抽时间放到码云上面一份🙏

膜拜大佬，能根据数据库字段和json返回值，手撸一个小程序出来        o(ﾟДﾟ)っ！！！

**Comment by bestming** [comment]
> 好的，谢谢您的关注，我这边抽时间放到码云上面一份🙏

你的mall和mall-app-web建议搞个tag，不然同步了macro的仓库，如果他有大的改动，你这边的小程序就用不了了（然后又不知道哪个版本对应哪个版本，）。

**Comment by TProgram** [comment]
@bestming 
hi bestming:
感谢您提的建议, 小程序与后台代码版本均已打 tag - V2.0.0 
并且将小程序代码与后台代码 同步至码云方便下载。

码云地址:
https://gitee.com/tPrograming/mall
https://gitee.com/tPrograming/mall-app-web

另外: 我这边可能关注该项目时间不太多，如果有兴趣和需求 欢迎一起维护该项目
