### ISSUE TITLE
后端项目少model

### ISSUE THREAD

**Issue by lianbitangjin** [TProgram/mall-app-web#2]
Error:(4, 28) java: 找不到符号
  符号:   类 UmsFeedBack
  位置: 程序包 com.macro.mall.model

**Comment by TProgram** [comment]
Hi lianbitangjin:
     谢谢你的关注。已经新增了 UmsFeedBack 在最近的 commmit中，请注意查看。

如需新增 表，可执行MBG 目录中 main 函数，重新处理。如果是windows 则需要修改一下目录配置。

![image](https://user-images.githubusercontent.com/67221860/102363921-e6b11d00-3ff0-11eb-8f5e-3a3a4511fd92.png)

如果仍有问题，欢迎讨论🤝
